apiVersion: v1
kind: ConfigMap
metadata:
  name: records-config
data:
  GREETING: Bonjour
  SECRET: THIS IS USED TO SIGN AND VERIFY JWT TOKENS, REPLACE IT WITH YOUR OWN
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://+:5030
  CACHE_ENABLED: "1"
  KAFKA_CONSUMER_URI: my-release-kafka.finalwork.svc.cluster.local:9092
  KAFKA_PRODUCER_URI: my-release-kafka-0.my-release-kafka-headless.finalwork.svc.cluster.local:9092
  GRPC_USER_SERVER_URI: http://myuser-user-chart:5025
---
apiVersion: v1
kind: Secret
metadata:
  name: records-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;Pooling=true;" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  DATABASE2_URI: {{ printf "User ID=%s;Password=%s;Host=%s;Port=%s;Database=%s;Pooling=true;" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase2  | b64enc | quote }}