apiVersion: batch/v1
kind: Job
metadata:
  name: hello-initdb
spec:
  template:
    metadata:
      name: hello-initdb
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          env:
            - name: DATABASE_URI
              value: "postgresql://myuser:passwd@postgres/myapp"
          image: postgres:latest
          command:
            - sh
            - "-c"
            - |
              psql $DATABASE_URI <<'EOF'
                create table client (id serial primary key, name varchar);
                insert into client (name) values ('Konstantin');
              EOF
  backoffLimit: 2