apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-chart.fullname" . }}
  labels:
    {{- include "hello-chart.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "hello-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    {{- end }}
      labels:
        {{- include "hello-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hello-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: delivery-secret
                  key: DATABASE_URI
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: GREETING
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: SECRET
            - name: ASPNETCORE_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: ASPNETCORE_ENVIRONMENT
            - name: ASPNETCORE_URLS
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: ASPNETCORE_URLS
            - name: CACHE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: CACHE_ENABLED
            - name: TEST_MODE
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: TEST_MODE
            - name: KAFKA_CONSUMER_URI
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: KAFKA_CONSUMER_URI
            - name: KAFKA_PRODUCER_URI
              valueFrom:
                configMapKeyRef:
                  name: delivery-config
                  key: KAFKA_PRODUCER_URI
                  
          ports:
            - name: http
              containerPort: {{- toYaml .Values.service.targetPort | nindent 16 }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{- toYaml .Values.service.targetPort | nindent 16 }}
              path: /versionDelivery
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: {{- toYaml .Values.service.targetPort | nindent 16 }}
              path: /versionDelivery
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
