{
 "title": "CaloriesApp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Calories Records Pods memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=\"myrecords-records-chart-75cd49fff7-b9wft\"}) by (pod)",
     "legendFormat": "myrecords-records-chart"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod=\"myrecords-postgresql-0\"}) by (pod)",
     "legendFormat": "myrecords-postgresql"
    }
   ]
  },
  {
   "title": "Calories Records Pods CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod=\"myrecords-postgresql-0\"}[1m])) by (pod)",
     "legendFormat": "myrecords-postgresql"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod=\"myrecords-records-chart-75cd49fff7-b9wft\"}[1m])) by (pod)",
     "legendFormat": "myrecords-records-chart"
    }
   ]
  },
  {
   "title": "Http Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(http_request_duration_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{action=~\"(.*)[CaloriesRecords|VersionRecords|token]\"}[2m])) * 1000"
    },
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_seconds_bucket{action=~\"(.*)[CaloriesRecords|VersionRecords]\"}[2m])) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_seconds_bucket{action=~\"(.*)[CaloriesRecords|VersionRecords|token]\"}[2m])) * 1000"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_received_total[2m])"
    }
   ]
  },
  {
   "title": "Nginx codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "Enginx Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"(.*)[CaloriesRecords|VersionRecords|token]\"}[2m])) * 1000"
    },
    {
     "expr": "histogram_quantile(0.99, rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"(.*)[CaloriesRecords|VersionRecords|token]\"}[2m])) * 1000"
    },
    {
     "expr": "histogram_quantile(0.5, rate(nginx_ingress_controller_request_duration_seconds_bucket{path=~\"(.*)[CaloriesRecords|VersionRecords|token]\"}[2m])) * 1000"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_nginx_process_requests_total[2m])"
    }
   ]
  }
 ]
}