prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
grafana:
  sidecar:
    dashboards:
      enabled: true
      labels:
        grafana_dashboard: "1"